apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: tileserver-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tileserver-app
    spec:
      containers:
      - name: tileserver
        image: klokantech/tileserver-gl:latest
        ports:
        - containerPort: 80
