apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: gatekeeper-client
spec:
  replicas: 128
  template:
    metadata:
      labels:
        app: gatekeeper-client
        stage: test
    spec:
      containers:
      - name: gatekeeper-client
        image: kevindyer/gatekeeper-client:v1.3
        env:
        - name: SERVER_HOSTNAME
          value: "http://gatekeeper-server"
        volumeMounts:
        - name: client-storage
          mountPath: /opt/data
      volumes:
      - name: client-storage
        emptyDir: {}
