kind: Service
apiVersion: v1
metadata:
  name: gatekeeper-server
spec:
  selector:
    app: gatekeeper-server
  ports:
    - protocol: TCP
      port: 80
  type: NodePort
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: gatekeeper-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gatekeeper-server
        stage: test
    spec:
      containers:
      - name: gatekeeper-server
        image: kevindyer/gatekeeper-server:v1.2
        env:
        - name: PORT
          value: "80"
