kind: PersistentVolume
apiVersion: v1
metadata:
  name: tileserver-data
spec:
  capacity:
    storage: 64Gi
  accessModes:
    - ReadOnlyMany
  nfs:
    server: cac-node-4.kevinmdyer.com
    path: "/opt/data/maps"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: tileserver-data
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 64Gi
---
kind: Service
apiVersion: v1
metadata:
  name: tileserver-app
spec:
  selector:
    app: tileserver-app
  ports:
    - protocol: TCP
      port: 80
  type: NodePort
---
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: tileserver-app
spec:
  replicas: 8
  template:
    metadata:
      labels:
        app: tileserver-app
    spec:
      containers:
      - name: tileserver-frontend
        image: klokantech/tileserver-gl:latest
        ports:
        - containerPort: 80
        volumeMounts:
            - name: tileserver-data
              mountPath: "/data"
      volumes:
      - name: tileserver-data
        persistentVolumeClaim:
          claimName: tileserver-data
